In [22]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
df = pd.read_csv('customer_import.csv')

# Define a function to concatenate address fields
def concatenate_address(row):
    return f"{row['Address']} {row['Address 2']}, {row['City']}, {row['State']}, {row['Country']} {row['Zip']}"

# Map CSV fields to Workable fields and transform the data accordingly
workable_data = {
    'Name': df.apply(lambda row: f"{row['First Name']} {row['Last Name']}", axis=1),
    'Email': df['Email'],
    'Phone': df['Phone'],
    'Address': df.apply(concatenate_address, axis=1),
    'Source': df['Referred By'],
    'Job Title': df['Position'],
    'Disqualified': df['Status'].apply(lambda status: True if status == 'Rejected' else False)
}

# Convert the dictionary to a pandas DataFrame
workable_df = pd.DataFrame(workable_data)

# Print the transformed DataFrame
print(workable_df)

# Export the transformed DataFrame to a new CSV file
workable_df.to_csv('workable_import.csv', index=False)

ParserError: Error tokenizing data. C error: Expected 33 fields in line 3, saw 34

In [31]:
import csv

# Open the CSV file in read mode
with open('customer_import.csv', newline='') as csvfile:
    # Create a CSV reader object
    reader = csv.reader(csvfile, delimiter=',', quotechar='"')

    # Iterate over each row in the CSV file
    for row in reader:
        # Print each row
        print(row)

['Candidate Id', 'First Name', 'Last Name', 'Email', 'Phone', 'Position', 'Status', 'Address', 'Address 2', 'City', 'State', 'Country', 'Zip', 'Available Date', 'Website Url', 'Linkedin Url', 'Twitter Username', 'Education Level', 'Education Institution Name', 'Gender', 'Ethnicity', 'Disability', 'Veteran Status', 'Application Date', 'Desired Salary', 'Referred By', 'References', 'Source', 'Resume File Id', 'Cover Letter File Id', 'Resume File', 'Cover Letter File', 'Offer Letter File']
['1', 'John', 'Doe', 'john.doe@email.com', '123-456-7890', 'Data Architect', 'Pending', '123 Main St', '', 'Anytown', 'CA', 'United States', '12345', '2023-02-01', 'https://www.johndoe.com', 'https://www.linkedin.com/in/johndoe', '@johndoe', "Bachelor's Degree", 'University of Tech', 'Male', 'Caucasian', '', '', '2023-01-15 09:30:00', '80000', 'Employee referral', 'Available upon request', 'RecruiterXYZ', '1', '', 'John_Doe_Resume.pdf', '', '']
['2', 'Jane', 'Smith', 'jane.smith@email.com', '987-654-3210', 'Data Architect', 'Interview Scheduled', '456 Oak St', '', 'Someville', 'NY', 'United States', '56789', '2023-03-15', 'https://www.janesmith.com', 'https://www.linkedin.com/in/janesmith', '@janesmith', "Master's Degree", 'Marketing Institute', 'Female', 'Hispanic', '', '', '2023-02-10 11:45:00', '60000', 'Job board', 'Previous employer', 'RecruiterABC', '2', '3', 'Jane_Smith_Resume.pdf', 'Jane_Smith_Cover_Letter.pdf', '', '']
['3', 'Michael', 'Jones', 'michael.jones@email.com', '555-123-4567', 'Data Architect', 'Offer Extended', '789 Pine St', '', 'Sometown', 'TX', 'United States', '67890', '2023-04-01', 'https://www.michaeljones.com', 'https://www.linkedin.com/in/michaeljones', '@michaeljones', "Bachelor's Degree", 'Data University', 'Male', 'African American', '', '', '2023-03-01 15:00:00', '70000', 'Employee referral', 'Available upon request', 'CompanyXYZ', '3', '', 'Michael_Jones_Resume.pdf', '', '']
['4', 'Sarah', 'Clark', 'sarah.clark@email.com', '111-222-3333', 'Data Architect', 'Rejected', '', '', 'Metroville', 'CA', 'United States', '54321', '', '', 'https://www.linkedin.com/in/sarahclark', '@sarahclark', "Master's Degree", 'HR Institute', 'Female', 'Caucasian', '', '', '2022-11-15 14:20:00', '90000', 'Job board', 'Previous colleague', 'RecruiterDEF', '4', '5', 'Sarah_Clark_Resume.pdf', 'Sarah_Clark_Cover_Letter.pdf', '', '']
['5', 'Chris', 'Nguyen', 'chris.nguyen@email.com', '999-888-7777', 'Data Architect', 'Pending', '987 Elm St', '', 'Cityville', 'NY', 'United States', '45678', '2023-05-01', 'https://www.chrisnguyen.com', 'https://www.linkedin.com/in/chrisnguyen', '@chrisnguyen', "Bachelor's Degree", 'Design College', 'Non-Binary', 'Asian', '', '', '2022-12-20 10:00:00', '75000', 'Employee referral', 'Available upon request', 'RecruiterGHI', '5', '', 'Chris_Nguyen_Resume.pdf', '', '']
['6', 'Emily', 'Kim', 'emily.kim@email.com', '444-555-6666', 'Data Architect', 'Interview Scheduled', '654 Birch St', '', 'Townsville', 'TX', 'United States', '34567', '2023-06-15', 'https://www.emilykim.com', 'https://www.linkedin.com/in/emilykim', '@emilykim', "Master's Degree", 'Business School', 'Female', 'Asian', '', '', '2023-06-01 12:15:00', '95000', 'Job board', 'Previous colleague', 'RecruiterJKL', '6', '7', 'Emily_Kim_Resume.pdf', 'Emily_Kim_Cover_Letter.pdf', '', '']
['7', 'Aaron', 'Lee', 'aaron.lee@email.com', '777-666-5555', 'Data Architect', 'Pending', '789 Maple St', '', 'Villagetown', 'CA', 'United States', '23456', '2023-07-01', 'https://www.aaronlee.com', 'https://www.linkedin.com/in/aaronlee', '@aaronlee', "Bachelor's Degree", 'Computer Science Institute', 'Male', 'Asian', '', '', '2023-01-10 09:45:00', '85000', 'Employee referral', 'Available upon request', 'RecruiterMNO', '7', '', 'Aaron_Lee_Resume.pdf', '', '']
['8', 'Olivia', 'Evans', 'olivia.evans@email.com', '222-333-4444', 'Data Architect', 'Offer Extended', '', '', 'Hometown', 'NY', 'United States', '12345', '2023-08-15', 'https://www.oliviaevans.com', 'https://www.linkedin.com/in/oliviaevans', '@oliviaevans', "Bachelor's Degree", 'Finance University', 'Female', 'Caucasian', '', '', '2023-08-01 14:30:00', '80000', 'Job board', 'Previous employer', 'RecruiterPQR', '8', '9', 'Olivia_Evans_Resume.pdf', 'Olivia_Evans_Cover_Letter.pdf', '', '']
['9', 'James', 'Miller', 'james.miller@email.com', '888-999-0000', 'Data Architect', 'Rejected', '', '', 'Techcity', 'TX', 'United States', '56789', '', '', 'https://www.linkedin.com/in/jamesmiller', '@jamesmiller', 'Associate Degree', 'Tech College', 'Male', 'Caucasian', '', '', '2023-09-15 16:00:00', '60000', 'Employee referral', 'Available upon request', 'RecruiterSTU', '9', '', 'James_Miller_Resume.pdf', '', '']
['10', 'Lily', 'Chen', 'lily.chen@email.com', '333-444-5555', 'Data Architect', 'Pending', '876 Pine St', '', 'Artstown', 'CA', 'United States', '45678', '2023-10-01', 'https://www.lilychen.com', 'https://www.linkedin.com/in/lilychen', '@lilychen', "Bachelor's Degree", 'Art Institute', 'Female', 'Asian', '', '', '2022-11-20 11:00:00', '70000', 'Job board', 'Previous colleague', 'RecruiterVWX', '10', '11', 'Lily_Chen_Resume.pdf', '', '']
['11', 'David', 'Johnson', 'david.johnson@email.com', '123-234-5678', 'Data Architect', 'Pending', '567 Oak St', '', 'Techville', 'CA', 'United States', '34567', '2023-11-01', 'https://www.davidjohnson.com', 'https://www.linkedin.com/in/davidjohnson', '@davidjohnson', "Master's Degree", 'Engineering College', 'Male', 'Caucasian', '', '', '2022-11-15 13:30:00', '90000', 'Employee referral', 'Available upon request', 'RecruiterYZA', '11', '', 'David_Johnson_Resume.pdf', '', '']
['12', 'Amy', 'Williams', 'amy.williams@email.com', '555-666-7777', 'Data Architect', 'Interview Scheduled', '987 Maple St', '', 'Greetown', 'NY', 'United States', '56789', '2023-12-15', 'https://www.amywilliams.com', 'https://www.linkedin.com/in/amywilliams', '@amywilliams', "Bachelor's Degree", 'Computer Science Institute', 'Female', 'Caucasian', '', '', '2022-12-01 10:45:00', '85000', 'Job board', 'Previous employer', 'RecruiterBCD', '12', '13', 'Amy_Williams_Resume.pdf', 'Amy_Williams_Cover_Letter.pdf', '', '']
['13', 'Robert', 'Lee', 'robert.lee@email.com', '333-222-1111', 'Data Architect', 'Rejected', '', '', 'Marketingtown', 'CA', 'United States', '43210', '', '', 'https://www.linkedin.com/in/robertlee', '@robertlee', "Bachelor's Degree", 'Marketing Institute', 'Male', 'Asian', '', '', '2022-12-20 09:30:00', '75000', 'Employee referral', 'Available upon request', 'RecruiterEFG', '13', '14', 'Robert_Lee_Resume.pdf', 'Robert_Lee_Cover_Letter.pdf', '', '']
['14', 'Michelle', 'Nguyen', 'michelle.nguyen@email.com', '777-888-9999', 'Data Architect', 'Pending', '876 Oak St', '', 'Codecity', 'TX', 'United States', '34567', '2024-01-01', 'https://www.michellenguyen.com', 'https://www.linkedin.com/in/michellenguyen', '@michellenguyen', "Master's Degree", 'Engineering College', 'Female', 'Asian', '', '', '2023-01-10 14:00:00', '90000', 'Job board', 'Previous colleague', 'RecruiterHIJ', '14', '15', 'Michelle_Nguyen_Resume.pdf', 'Michelle_Nguyen_Cover_Letter.pdf', '', '']
['15', 'Andrew', 'Smith', 'andrew.smith@email.com', '111-222-3333', 'Data Architect', 'Offer Extended', '789 Birch St', '', 'Datatown', 'NY', 'United States', '12345', '2024-01-15', 'https://www.andrewsmith.com', 'https://www.linkedin.com/in/andrewsmith', '@andrewsmith', "Bachelor's Degree", 'Data University', 'Male', 'Caucasian', '', '', '2024-04-01 15:45:00', '70000', 'Employee referral', 'Available upon request', 'RecruiterKLM', '15', '16', 'Andrew_Smith_Resume.pdf', 'Andrew_Smith_Cover_Letter.pdf', '', '']
['16', 'Karen', 'Johnson', 'karen.johnson@email.com', '444-555-6666', 'Data Architect', 'Interview Scheduled', '654 Elm St', '', 'Marketville', 'CA', 'United States', '45678', '2024-01-01', 'https://www.karenjohnson.com', 'https://www.linkedin.com/in/karenjohnson', '@karenjohnson', "Master's Degree", 'Marketing Institute', 'Female', 'Caucasian', '', '', '2023-12-01 12:15:00', '60000', 'Job board', 'Previous employer', 'RecruiterNOP', '16', '17', 'Karen_Johnson_Resume.pdf', 'Karen_Johnson_Cover_Letter.pdf', '', '']
['17', 'Justin', 'Kim', 'justin.kim@email.com', '999-888-7777', 'Data Architect', 'Pending', '876 Pine St', '', 'Techtown', 'TX', 'United States', '23456', '2024-01-15', 'https://www.justinkim.com', 'https://www.linkedin.com/in/justinkim', '@justinkim', "Bachelor's Degree", 'Computer Science Institute', 'Male', 'Asian', '', '', '2024-01-01 09:45:00', '85000', 'Employee referral', 'Available upon request', 'RecruiterQRS', '17', '', 'Justin_Kim_Resume.pdf', '', '']
['18', 'Grace', 'Li', 'grace.li@email.com', '222-333-4444', 'Data Architect', 'Rejected', '', '', 'Dataville', 'NY', 'United States', '56789', '2024-01-01', 'https://www.graceli.com', 'https://www.linkedin.com/in/graceli', '@graceli', "Bachelor's Degree", 'Data University', 'Female', 'Asian', '', '', '2023-05-15 16:00:00', '60000', 'Job board', 'Previous colleague', 'RecruiterTUV', '18', '', 'Grace_Li_Resume.pdf', '', '']
['19', 'Christopher', 'Brown', 'christopher.brown@email.com', '888-999-0000', 'Data Architect', 'Pending', '', '', 'Marketcity', 'CA', 'United States', '12345', '', '', 'https://www.linkedin.com/in/christopherbrown', '@christopherbrown', "Master's Degree", 'Marketing Institute', 'Male', 'African American', '', '', '2023-06-01 11:00:00', '70000', 'Employee referral', 'Available upon request', 'RecruiterWXY', '19', '20', 'Christopher_Brown_Resume.pdf', 'Christopher_Brown_Cover_Letter.pdf', '', '']
['20', 'Isabella', 'Wang', 'isabella.wang@email.com', '333-444-5555', 'Data Architect', 'Offer Extended', '876 Oak St', '', 'Codeville', 'TX', 'United States', '45678', '2024-01-15', 'https://www.isabellawang.com', 'https://www.linkedin.com/in/isabellawang', '@isabellawang', "Bachelor's Degree", 'Computer Science Institute', 'Female', 'Asian', '', '', '2024-01-01 14:30:00', '90000', 'Job board', 'Previous employer', 'RecruiterZAB', '20', '21', 'Isabella_Wang_Resume.pdf', 'Isabella_Wang_Cover_Letter.pdf', '', '']
['21', 'Justin', 'Johnson', 'justin.kim@email.com', '555-666-7777', 'Data Architect', 'Pending', '987 Pine St', '', 'Dataville', 'CA', 'United States', '23456', '2024-01-01', 'https://www.marcusjohnson.com', 'https://www.linkedin.com/in/marcusjohnson', '@marcusjohnson', "Master's Degree", 'Engineering College', 'Male', 'African American', '', '', '2024-01-10 09:45:00', '80000', 'Employee referral', 'Available upon request', 'RecruiterBCD', '21', '', 'Marcus_Johnson_Resume.pdf', '', '']
['22', 'Sophia', 'Lee', 'sophia.lee@email.com', '222-333-4444', 'Data Architect', 'Rejected', '', '', 'Marketcity', 'CA', 'United States', '12345', '', '', 'https://www.linkedin.com/in/sophialee', '@sophialee', "Bachelor's Degree", 'Marketing Institute', 'Female', 'Asian', '', '', '2024-01-15 14:00:00', '75000', 'Job board', 'Previous colleague', 'RecruiterEFG', '22', '23', 'Sophia_Lee_Resume.pdf', 'Sophia_Lee_Cover_Letter.pdf', '', '']
[]

In [29]:
import csv

# Define the input and output file paths
input_file = "customer_import.csv"
output_file = "cleaned_customer_import.csv"

# Open the input and output CSV files
with open(input_file, 'r', newline='', encoding='utf-8-sig') as csvfile, \
     open(output_file, 'w', newline='', encoding='utf-8') as outfile:

    # Create a CSV reader and writer objects
    reader = csv.reader(csvfile)
    writer = csv.writer(outfile)

    # Write the header row to the output CSV file
    header = next(reader)
    writer.writerow(header)

    # Iterate over each row in the input CSV file
    for row in reader:
        # Check if the row has the expected number of fields
        if len(row) == len(header):
            # Write the row to the output CSV file
            writer.writerow(row)
        else:
            print(f"Ignoring row with unexpected number of fields: {row}")

Ignoring row with unexpected number of fields: ['2', 'Jane', 'Smith', 'jane.smith@email.com', '987-654-3210', 'Data Architect', 'Interview Scheduled', '456 Oak St', '', 'Someville', 'NY', 'United States', '56789', '2023-03-15', 'https://www.janesmith.com', 'https://www.linkedin.com/in/janesmith', '@janesmith', "Master's Degree", 'Marketing Institute', 'Female', 'Hispanic', '', '', '2023-02-10 11:45:00', '60000', 'Job board', 'Previous employer', 'RecruiterABC', '2', '3', 'Jane_Smith_Resume.pdf', 'Jane_Smith_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['4', 'Sarah', 'Clark', 'sarah.clark@email.com', '111-222-3333', 'Data Architect', 'Rejected', '', '', 'Metroville', 'CA', 'United States', '54321', '', '', 'https://www.linkedin.com/in/sarahclark', '@sarahclark', "Master's Degree", 'HR Institute', 'Female', 'Caucasian', '', '', '2022-11-15 14:20:00', '90000', 'Job board', 'Previous colleague', 'RecruiterDEF', '4', '5', 'Sarah_Clark_Resume.pdf', 'Sarah_Clark_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['6', 'Emily', 'Kim', 'emily.kim@email.com', '444-555-6666', 'Data Architect', 'Interview Scheduled', '654 Birch St', '', 'Townsville', 'TX', 'United States', '34567', '2023-06-15', 'https://www.emilykim.com', 'https://www.linkedin.com/in/emilykim', '@emilykim', "Master's Degree", 'Business School', 'Female', 'Asian', '', '', '2023-06-01 12:15:00', '95000', 'Job board', 'Previous colleague', 'RecruiterJKL', '6', '7', 'Emily_Kim_Resume.pdf', 'Emily_Kim_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['8', 'Olivia', 'Evans', 'olivia.evans@email.com', '222-333-4444', 'Data Architect', 'Offer Extended', '', '', 'Hometown', 'NY', 'United States', '12345', '2023-08-15', 'https://www.oliviaevans.com', 'https://www.linkedin.com/in/oliviaevans', '@oliviaevans', "Bachelor's Degree", 'Finance University', 'Female', 'Caucasian', '', '', '2023-08-01 14:30:00', '80000', 'Job board', 'Previous employer', 'RecruiterPQR', '8', '9', 'Olivia_Evans_Resume.pdf', 'Olivia_Evans_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['12', 'Amy', 'Williams', 'amy.williams@email.com', '555-666-7777', 'Data Architect', 'Interview Scheduled', '987 Maple St', '', 'Greetown', 'NY', 'United States', '56789', '2023-12-15', 'https://www.amywilliams.com', 'https://www.linkedin.com/in/amywilliams', '@amywilliams', "Bachelor's Degree", 'Computer Science Institute', 'Female', 'Caucasian', '', '', '2022-12-01 10:45:00', '85000', 'Job board', 'Previous employer', 'RecruiterBCD', '12', '13', 'Amy_Williams_Resume.pdf', 'Amy_Williams_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['13', 'Robert', 'Lee', 'robert.lee@email.com', '333-222-1111', 'Data Architect', 'Rejected', '', '', 'Marketingtown', 'CA', 'United States', '43210', '', '', 'https://www.linkedin.com/in/robertlee', '@robertlee', "Bachelor's Degree", 'Marketing Institute', 'Male', 'Asian', '', '', '2022-12-20 09:30:00', '75000', 'Employee referral', 'Available upon request', 'RecruiterEFG', '13', '14', 'Robert_Lee_Resume.pdf', 'Robert_Lee_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['14', 'Michelle', 'Nguyen', 'michelle.nguyen@email.com', '777-888-9999', 'Data Architect', 'Pending', '876 Oak St', '', 'Codecity', 'TX', 'United States', '34567', '2024-01-01', 'https://www.michellenguyen.com', 'https://www.linkedin.com/in/michellenguyen', '@michellenguyen', "Master's Degree", 'Engineering College', 'Female', 'Asian', '', '', '2023-01-10 14:00:00', '90000', 'Job board', 'Previous colleague', 'RecruiterHIJ', '14', '15', 'Michelle_Nguyen_Resume.pdf', 'Michelle_Nguyen_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['15', 'Andrew', 'Smith', 'andrew.smith@email.com', '111-222-3333', 'Data Architect', 'Offer Extended', '789 Birch St', '', 'Datatown', 'NY', 'United States', '12345', '2024-01-15', 'https://www.andrewsmith.com', 'https://www.linkedin.com/in/andrewsmith', '@andrewsmith', "Bachelor's Degree", 'Data University', 'Male', 'Caucasian', '', '', '2024-04-01 15:45:00', '70000', 'Employee referral', 'Available upon request', 'RecruiterKLM', '15', '16', 'Andrew_Smith_Resume.pdf', 'Andrew_Smith_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['16', 'Karen', 'Johnson', 'karen.johnson@email.com', '444-555-6666', 'Data Architect', 'Interview Scheduled', '654 Elm St', '', 'Marketville', 'CA', 'United States', '45678', '2024-01-01', 'https://www.karenjohnson.com', 'https://www.linkedin.com/in/karenjohnson', '@karenjohnson', "Master's Degree", 'Marketing Institute', 'Female', 'Caucasian', '', '', '2023-12-01 12:15:00', '60000', 'Job board', 'Previous employer', 'RecruiterNOP', '16', '17', 'Karen_Johnson_Resume.pdf', 'Karen_Johnson_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['19', 'Christopher', 'Brown', 'christopher.brown@email.com', '888-999-0000', 'Data Architect', 'Pending', '', '', 'Marketcity', 'CA', 'United States', '12345', '', '', 'https://www.linkedin.com/in/christopherbrown', '@christopherbrown', "Master's Degree", 'Marketing Institute', 'Male', 'African American', '', '', '2023-06-01 11:00:00', '70000', 'Employee referral', 'Available upon request', 'RecruiterWXY', '19', '20', 'Christopher_Brown_Resume.pdf', 'Christopher_Brown_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['20', 'Isabella', 'Wang', 'isabella.wang@email.com', '333-444-5555', 'Data Architect', 'Offer Extended', '876 Oak St', '', 'Codeville', 'TX', 'United States', '45678', '2024-01-15', 'https://www.isabellawang.com', 'https://www.linkedin.com/in/isabellawang', '@isabellawang', "Bachelor's Degree", 'Computer Science Institute', 'Female', 'Asian', '', '', '2024-01-01 14:30:00', '90000', 'Job board', 'Previous employer', 'RecruiterZAB', '20', '21', 'Isabella_Wang_Resume.pdf', 'Isabella_Wang_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: ['22', 'Sophia', 'Lee', 'sophia.lee@email.com', '222-333-4444', 'Data Architect', 'Rejected', '', '', 'Marketcity', 'CA', 'United States', '12345', '', '', 'https://www.linkedin.com/in/sophialee', '@sophialee', "Bachelor's Degree", 'Marketing Institute', 'Female', 'Asian', '', '', '2024-01-15 14:00:00', '75000', 'Job board', 'Previous colleague', 'RecruiterEFG', '22', '23', 'Sophia_Lee_Resume.pdf', 'Sophia_Lee_Cover_Letter.pdf', '', '']
Ignoring row with unexpected number of fields: []

In [34]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_customer_import.csv')

df.head(5)

,Candidate Id,First Name,Last Name,Email,Phone,Position,Status,Address,Address 2,City,...,Application Date,Desired Salary,Referred By,References,Source,Resume File Id,Cover Letter File Id,Resume File,Cover Letter File,Offer Letter File
0,1,John,Doe,john.doe@email.com,123-456-7890,Data Architect,Pending,123 Main St,NaN,Anytown,...,2023-01-15 09:30:00,80000,Employee referral,Available upon request,RecruiterXYZ,1,NaN,John_Doe_Resume.pdf,NaN,NaN
1,3,Michael,Jones,michael.jones@email.com,555-123-4567,Data Architect,Offer Extended,789 Pine St,NaN,Sometown,...,2023-03-01 15:00:00,70000,Employee referral,Available upon request,CompanyXYZ,3,NaN,Michael_Jones_Resume.pdf,NaN,NaN
2,5,Chris,Nguyen,chris.nguyen@email.com,999-888-7777,Data Architect,Pending,987 Elm St,NaN,Cityville,...,2022-12-20 10:00:00,75000,Employee referral,Available upon request,RecruiterGHI,5,NaN,Chris_Nguyen_Resume.pdf,NaN,NaN
3,7,Aaron,Lee,aaron.lee@email.com,777-666-5555,Data Architect,Pending,789 Maple St,NaN,Villagetown,...,2023-01-10 09:45:00,85000,Employee referral,Available upon request,RecruiterMNO,7,NaN,Aaron_Lee_Resume.pdf,NaN,NaN
4,9,James,Miller,james.miller@email.com,888-999-0000,Data Architect,Rejected,NaN,NaN,Techcity,...,2023-09-15 16:00:00,60000,Employee referral,Available upon request,RecruiterSTU,9,NaN,James_Miller_Resume.pdf,NaN,NaN

In [49]:
import pandas as pd
import csv

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_customer_import.csv')

# Define a function to concatenate address fields
def concatenate_address(row):
    # Extract individual address components
    address = row['Address']
    address_2 = row['Address 2']
    city = row['City']
    state = row['State']
    country = row['Country']
    zip_code = row['Zip']
    
    # Create a list to store all address components
    components = [str(address), str(address_2), str(city), str(state), str(country), str(zip_code)]
    
    # Join all components with commas
    concatenated_address = ', '.join(components)
    
    return concatenated_address

# Map CSV fields to Workable fields and transform the data accordingly
workable_data = {
    'Name': df.apply(lambda row: f"{row['First Name']} {row['Last Name']}", axis=1),
    'Email': df['Email'],
    'Phone': df['Phone'],
    'Address': df.apply(concatenate_address, axis=1),
    'Source': df['Referred By'],
    'Job Title': df['Position'], # Position (it should match exactly with the corresponding one in Workable)
    'Disqualified': df['Status'].apply(lambda status: True if status == 'Rejected' else False)
}

# Convert the dictionary to a pandas DataFrame
workable_df = pd.DataFrame(workable_data)

# Print the transformed DataFrame
print(workable_df)

# Export the transformed DataFrame to a new CSV file
workable_df.to_csv('workable_import.csv', index=False)

             Name                    Email         Phone  \
0        John Doe       john.doe@email.com  123-456-7890
1   Michael Jones  michael.jones@email.com  555-123-4567
2    Chris Nguyen   chris.nguyen@email.com  999-888-7777
3       Aaron Lee      aaron.lee@email.com  777-666-5555
4    James Miller   james.miller@email.com  888-999-0000
5       Lily Chen      lily.chen@email.com  333-444-5555
6   David Johnson  david.johnson@email.com  123-234-5678
7      Justin Kim     justin.kim@email.com  999-888-7777
8        Grace Li       grace.li@email.com  222-333-4444
9  Justin Johnson     justin.kim@email.com  555-666-7777

                                             Address             Source  \
0  123 Main St, nan, Anytown, CA, United States, ...  Employee referral
1  789 Pine St, nan, Sometown, TX, United States,...  Employee referral
2  987 Elm St, nan, Cityville, NY, United States,...  Employee referral
3  789 Maple St, nan, Villagetown, CA, United Sta...  Employee referral
4       nan, nan, Techcity, TX, United States, 56789  Employee referral
5  876 Pine St, nan, Artstown, CA, United States,...          Job board
6  567 Oak St, nan, Techville, CA, United States,...  Employee referral
7  876 Pine St, nan, Techtown, TX, United States,...  Employee referral
8      nan, nan, Dataville, NY, United States, 56789          Job board
9  987 Pine St, nan, Dataville, CA, United States...  Employee referral

        Job Title  Disqualified
0  Data Architect         False
1  Data Architect         False
2  Data Architect         False
3  Data Architect         False
4  Data Architect          True
5  Data Architect         False
6  Data Architect         False
7  Data Architect         False
8  Data Architect          True
9  Data Architect         False

In [1]:
import pandas as pd
import csv

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_customer_import.csv')

# Define a function to concatenate address fields
def concatenate_address(row):
    # Extract individual address components
    address = row['Address']
    address_2 = row['Address 2']
    city = row['City']
    state = row['State']
    country = row['Country']
    zip_code = row['Zip']
    
    # Create a list to store all address components
    components = [str(address), str(address_2), str(city), str(state), str(country), str(zip_code)]
    
    # Join all components with commas
    concatenated_address = ', '.join(components)
    
    return concatenated_address

# Define a function to generate the email suffix
def generate_suffix(first_name, last_name):
    suffix = (first_name[0] + last_name[:2]).lower() + "_"
    return suffix

# Map CSV fields to Workable fields and transform the data accordingly
workable_data = {
    'Name': df.apply(lambda row: f"{row['First Name']} {row['Last Name']}", axis=1),
    'Email': df.apply(lambda row: f"{generate_suffix(row['First Name'], row['Last Name'])}{row['Email']}", axis=1),
    'Phone': df['Phone'],
    'Address': df.apply(concatenate_address, axis=1),
    'Source': df['Referred By'],
    'Job Title': df['Position'], # Position (it should match exactly with the corresponding one in Workable)
    'Disqualified': df['Status'].apply(lambda status: True if status == 'Rejected' else False)
}

# Convert the dictionary to a pandas DataFrame
workable_df = pd.DataFrame(workable_data)

# Print the transformed DataFrame
print(workable_df)

# Export the transformed DataFrame to a new CSV file
workable_df.to_csv('workable_import.csv', index=False)

             Name                        Email         Phone  \
0        John Doe       jdo_john.doe@email.com  123-456-7890
1   Michael Jones  mjo_michael.jones@email.com  555-123-4567
2    Chris Nguyen   cng_chris.nguyen@email.com  999-888-7777
3       Aaron Lee      ale_aaron.lee@email.com  777-666-5555
4    James Miller   jmi_james.miller@email.com  888-999-0000
5       Lily Chen      lch_lily.chen@email.com  333-444-5555
6   David Johnson  djo_david.johnson@email.com  123-234-5678
7      Justin Kim     jki_justin.kim@email.com  999-888-7777
8        Grace Li       gli_grace.li@email.com  222-333-4444
9  Justin Johnson     jjo_justin.kim@email.com  555-666-7777

                                             Address             Source  \
0  123 Main St, nan, Anytown, CA, United States, ...  Employee referral
1  789 Pine St, nan, Sometown, TX, United States,...  Employee referral
2  987 Elm St, nan, Cityville, NY, United States,...  Employee referral
3  789 Maple St, nan, Villagetown, CA, United Sta...  Employee referral
4       nan, nan, Techcity, TX, United States, 56789  Employee referral
5  876 Pine St, nan, Artstown, CA, United States,...          Job board
6  567 Oak St, nan, Techville, CA, United States,...  Employee referral
7  876 Pine St, nan, Techtown, TX, United States,...  Employee referral
8      nan, nan, Dataville, NY, United States, 56789          Job board
9  987 Pine St, nan, Dataville, CA, United States...  Employee referral

        Job Title  Disqualified
0  Data Architect         False
1  Data Architect         False
2  Data Architect         False
3  Data Architect         False
4  Data Architect          True
5  Data Architect         False
6  Data Architect         False
7  Data Architect         False
8  Data Architect          True
9  Data Architect         False